---
FussyPedant/Ruby:
  Enabled: true

FussyPedant/Rails:
  Enabled: true

FussyPedant/RSpec:
  Enabled: true

FussyPedant/Rake:
  Enabled: true

FussyPedant/FactoryBot:
  Enabled: true

FussyPedant/FactoryBot/TraitsAlphabeticalOrder:
  Enabled: true
  Include:
    - 'spec/support/factories/**/*.rb'

FussyPedant/Rails/ServiceCallPattern:
  Enabled: true
  ServicesDirectory: ''
  Include:
    - 'app/services/**/*.rb'
